{% set version = "1.0.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rmdformats
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rmdformats_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rmdformats/rmdformats_{{ version }}.tar.gz
  sha256: a4a6bb1778f6e5dd930b5804c7717e0175879c3770436ef6a6b86159824673ff

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bookdown
    - r-htmltools
    - r-knitr
    - r-rmarkdown
  run:
    - r-base
    - r-bookdown
    - r-htmltools
    - r-knitr
    - r-rmarkdown

test:
  commands:
    - $R -e "library('rmdformats')"           # [not win]
    - "\"%R%\" -e \"library('rmdformats')\""  # [win]

about:
  home: https://github.com/juba/rmdformats
  license: GPL-2.0-or-later
  summary: HTML formats and templates for 'rmarkdown' documents, with some extra features such as automatic table of contents, lightboxed figures, dynamic crosstab helper.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
